# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2a6a627ac6c7ed95fa2605e1118205a38b5790dcd2709affa7d011a02db8db49e5d42e3442dc65e6caa9256ea81af099843b4c7ccfaf59d1defd104c5ce2d0c7

test:
  secret_key_base: d805791d6770f572c31d4eba4890aa92f7e16b4556d047244d68d6ea54067cc6da706a337bc156b399268bbc1e84d2f847fce34b8d41fcb094294a909815d3fa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
